module.exports = Object.freeze({
  USER: 'User',
  REALM: 'Realm',
  STUDENT: 'Student',
  CLASSES: 'CLASSES',
  CLASS: 'CLASS',
  CLAN: 'CLAN',
  CLAN_TRESHOLDS: 'CLAN_TRESHOLDS',
  BACKUP_LIST: 'BACKUP_LIST',
  BACKUP: 'BACKUP',
  GOOGE_USER: 'GOOGE_USER',
  REGISTER_TOKEN: 'REGISTER_TOKEN'
})
