module.exports = Object.freeze({
  NAME: 'NAME',
  CLAN: 'CLAN',
  CLASS: 'CLASS',
  LEVEL: 'LEVEL',
  CUMULATIVE_XP: 'CUMULATIVE_XP',
  XP_MODIFIER: 'XP_MODIFIER',
  LESSON_XP: 'LESSON_XP',
  MANA_POINTS: 'MANA_POINTS',
  MANA_MODIFIER: 'MANA_MODIFIER',
  SKILL_COUNTER: 'SKILL_COUNTER',
  PET_FOOD: 'PET_FOOD',
  CURSE_POINTS: 'CURSE_POINTS',
  // NOT_PRESENT: 'NOT_PRESENT',
  DUEL_COUNT: 'DUEL_COUNT',
  STUDENT_ID: 'STUDENT_ID'
});
